### ISSUE TITLE
Too Many Tanks May Cause Clipping

### ISSUE THREAD

**Issue by FoeFear** [aehmttw/Tanks#43]
This was something I noticed while using the level editor. If a level has performance issues, projectiles and tanks can bypass through walls. It isn't a significant issue if you are not using more than the amount of tanks found in the video below.

https://www.youtube.com/watch?v=F-OBdusHHy4

**Comment by dabigf5** [comment]
this bug is known as "glipping"; the reason it happens is that the game accounts for lag by teleporting things forward (bullets, tanks, etc) so they move at the speed that they would have moved had the game not lagged, but these teleports do not account for collision checks, thus tanks going inside and through obstacles, it should be fixed in the more recent 1.5.2 dev builds, but it is present in 1.5.1 (the version on steam at the time of writing)

**Comment by FoeFear** [comment]
> this bug is known as "glipping"; the reason it happens is that the game accounts for lag by teleporting things forward (bullets, tanks, etc) so they move at the speed that they would have moved had the game not lagged, but these teleports do not account for collision checks, thus tanks going inside and through obstacles, it should be fixed in the more recent 1.5.2 dev builds, but it is present in 1.5.1 (the version on steam at the time of writing)

Ah, I didn't know it is already fixed in the dev build. I appreciate the heads up!
